### ISSUE TITLE
Czy skrypt dalej ma działać?

### ISSUE THREAD

**Issue by pogarek** [consi/medisnip#1]
Hej
Ciekawy pomysł. Już mialem napisać coś podobnego dla siebie (C#), a tu proszę :-)

W każdym razie spróbowalem odpalić skrypt (Windows 10, python 2.7) i mi nie działa:

```
Traceback (most recent call last):
  File "medisnip.py", line 171, in <module>
    medisnip = MediSnip(configuration_file=args.config)
  File "medisnip.py", line 34, in __init__
    raise Exception('Cannot open configuration file ({file})!'.format(file=configuration_file))
Exception: Cannot open configuration file (~/.medisnip.yml)!
```

Przy uruchomieniu -c example_config.yml dostaję błąd 404 .. : 
```
Traceback (most recent call last):
  File "medisnip.py", line 171, in <module>
    medisnip = MediSnip(configuration_file=args.config)
  File "medisnip.py", line 40, in __init__
    self.medicover = zeep.Client(self.MEDICOVER_API)
  File "C:\Python27\medisnip\lib\site-packages\zeep\client.py", line 62, in __init__
    wsdl, self.transport, settings=self.settings)
  File "C:\Python27\medisnip\lib\site-packages\zeep\wsdl\wsdl.py", line 82, in __init__
    document = self._get_xml_document(location)
  File "C:\Python27\medisnip\lib\site-packages\zeep\wsdl\wsdl.py", line 143, in _get_xml_document
    location, self.transport, self.location, settings=self.settings)
  File "C:\Python27\medisnip\lib\site-packages\zeep\loader.py", line 74, in load_external
    content = transport.load(url)
  File "C:\Python27\medisnip\lib\site-packages\zeep\transports.py", line 110, in load
    content = self._load_remote_data(url)
  File "C:\Python27\medisnip\lib\site-packages\zeep\transports.py", line 127, in _load_remote_data
    response.raise_for_status()
  File "C:\Python27\medisnip\lib\site-packages\requests\models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://api.medicover.pl/MOB/MOB.WebServices/Service.svc/basic?singleWsdl
```

Jak zrobić escaping # jeśli mam go w haśle ? :-)
Pozdrawiam

**Comment by consi** [comment]
According to yaml # escape: https://stackoverflow.com/questions/13711444/write-in-yaml-in-the-string

Also, be awarie that script mamy be outdated. You can get new api urls from Medicover APK after decompilation.

Currently I dont have active medicover subscription to test this
